# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KdsA3rZ4de_tBQ_pjWzxRVGSx4e4ZiW3
"""

##1
def area(length,width):
  return length * width

length = int(input('Enter the length of the place in meters'))
width = (input('Enter the width of the place in meters'))

if int(area(length,width)) < 1000:
  print('Small')
elif int(area(length,width)) > 1000 and int(area(length,width)) < 3000:
  print('Medium')
else:
  print('Large')

##2
def bmi(height,weight):
  return weight/(height**2)

height = float(input('Enter the height in meters'))
weight = float(input('Enter the weight in kg'))

if float(bmi(height,weight)) < 18:
  print('Your underweight , eat more caloric dense foods and excercise')
elif float(bmi(height,weight)) > 19 and float(bmi(height,weight)) < 23:
  print('You have a healthy bmi , maintain the same diet and exercise')
else:
  print('You are over weight , stay in a caloric deficit and exercise\')

##3
class students:
  def __init__(self):
    self.student={}

  def add_student(self,subject,student_id,student_name,grade):
    if student_id not in self.student:
      self.student[student_id] = {'name':student_name,'subject':subject,'grade':grade}
    elif student_id in self.student:
      print('student ID present')

  def update_student(self):
    a = input('enter student id')

    if a in self.student:
      upd = input('What to update')
      if upd =='grade':
        grade1 = input('Enter the grade')
        for key,value in self.student.items():
          if key == a:
            self.student[key][upd]=grade1

    else:
      print('Not found')


  def generate_report(self):
      print(" Report:")
      for key,value in self.student.items():
          print(key,value)

s=students()

while 1:
  print("1 to add /n 2 to update /n 3 to generate report /n 0 to exit")
  a=input()
  if a == '1':

    s.add_student('Maths',101,'surya','A')
    s.add_student('Maths',102,'surya','A')
  elif a=='2':
    s.update_student()
  elif a=='3':
    s.generate_report()
  elif a=='0':
    break

##4

tv={'children':['ben 10','tom and jerry'],
    'teen':['Aragon','Narnia'],
    'Adult':['The Boys','Fallout'],
    'Senior':['The Office','Greys Anatomy']}

a = int(input("enter your age"))

if a < 10:
  ke = 'children'
  print("children reccomendation")
  print(tv[ke])
elif a >10 and a < 18:
  ke = 'teen'
  print("teen reccomendation")
  print(tv[ke])
elif a >18 and a < 55:
  ke = 'Adult'
  print("Adult reccomendation")
  print(tv[ke])
else:
  ke = 'Senior'
  print("Senior reccomendation")
  print(tv[ke])

##5
subId=[10,12,11,14,15,16,19,22,55,88,97,95]
for i in range(0,len(subId)):
  if i%2 == 0:
    print(f'SubId:{i} is a potential subscriber')

##6
pasword = 'qwerty123'

while 1:
  print('Welcome Please enter the password to further continue')
  word = input('Enter the password')
  if word == pasword:
    print('Welcome you have logged in')
    break
  else:
    print('Wrong password please try again')

##7

def aggre(list1):
  a=0
  for i in range(0,len(list1)):
    a=a+i
  avg=a/len(list1)
  if avg < 5:
    print('The customer rating is low need to work on product')
  elif avg > 5 and avg <7:
    print('Customer rating is okay , room for improvement')
  else:
    print('Customer rating is great, please maintain the same')

list1 = [1,2,3,4,5,6,7,8]
aggre(list1)

##8
def count_vo(stri):
  count=0
  for i in stri:
    if i in ['a','e','i','o','u']:
      count = count +1
  return count
word = input('enter the comment')

a=count_vo(word)
print(f'the comment {word} has {a} vowels')

##9
import datetime
print(datetime.datetime.now())

from logging import exception
##10
def loan_replayment():
  account_money = 10000
  amount = int(input('enter the repayment amount amount'))


  if account_money<amount:
    raise ValueError("Loan amount less ")
  elif account_money == 0:
    raise exception ('Loan amount clerared')


while 1:
  try:

     loan_replayment()
  except ValueError as ve:
     print(f'Error {ve}')
  except Exception as ex:
      print(f'Error {ex}')
  print('Would you like to continue another transaction press Y or N')
  ans = input()
  if ans=='Y':
    loan_replayment()
  elif ans == 'N':
    print('exiting..')
    break

##11
try:
  name = input('Enter the name ')
  age = int(input('Enter age'))
except ValueError:
  print('error Enter the correct age')

##12
def addition(x, y):
    return x + y

def subtraction(x, y):
    return x - y

def multiplication(x, y):
    return x * y

def division(x, y):
  try:
      return x/y


  except ZeroDivisionError:
    print('The variable cannot be divided')

while 1:
  print("Choose a mathematical operation:")
  print("1. Addition")
  print("2. Subtraction")
  print("3. Multiplication")
  print("4. Division")
  print("0. Exit")


  choice = input("Enter your choice : ")

  num1 = float(input("Enter the first number: "))
  num2 = float(input("Enter the second number: "))

  if choice == '1':
      result = addition(num1, num2)
  elif choice == '2':
      result = subtraction(num1, num2)
  elif choice == '3':
      result = multiplication(num1, num2)
  elif choice == '4':
      result = division(num1, num2)
  elif choice == '0':
      break
  else:
      result = "Invalid choice! Please choose a valid operation."

  print("Result:", result)

##13

def update( ):
  with open (r"D:\Assessement\New Text Document.txt",'w') as file:
    file.write('TEXT')

update()

##14
with open(r"D:\Assessement\New Text Document.txt",'r') as file:
  for i in file:
    print(i)

##15
word = 'Hello'

with open(r"D:\Assessement\New Text Document.txt",'w') as file:
  for i in word:
    file.write(i)
    print(i)