# -*- coding: utf-8 -*-
"""LVADSUSR198_VishalRao_IA-2_Lab-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16gZn3uJR2C1DN1nu3oLrpqw-9gQ5Sw5c
"""

import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder, LabelEncoder,StandardScaler
import matplotlib.pyplot as plt


# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint

# Tree Visualisation
from sklearn.tree import export_graphviz
from IPython.display import Image
import graphviz

df= pd.read_csv('/content/winequality-red.csv')

df

## null values
df.isna().sum()

for i in df.columns:
  df[i]=df[i].fillna(df[i].median())

df.isna().sum()

##basic Vizualization
sns.pairplot(df)

sns.boxplot(df['fixed acidity'])

sns.boxplot(df['sulphates'])

df['quality'].plot(kind='bar')

df.corr()

y = df['quality']
x = df.drop('quality',axis = 1)
y

X_train, X_Test, Y_train,Y_test = train_test_split(x,y,train_size=0.7)

scale = StandardScaler()
X_train = scale.fit_transform(X_train)
X_Test = scale.fit_transform(X_Test)

##Model fitting
model = RandomForestClassifier()
model.fit(X_train, Y_train)

##Predicting the values
y_pred = model.predict(X_Test)

##Metrics
accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy:", accuracy*100)

print("Confusion Matrix: ",
confusion_matrix(Y_test, y_pred))