# -*- coding: utf-8 -*-
"""LVADSUSR198 _Vishal Rao_FA_lab-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BW5zg-6X6VKZ3fz34kJmzC5szpvjjNwP
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.ensemble  import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,f1_score,mean_squared_error
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/Fare prediction.csv')
df

##Pre Processing
df.info()
print(df.isna().sum())
## No missing values
print(df.duplicated().sum())
## the data does not have any duplicated values

df_num = df.select_dtypes(include=np.number)
df_num

enc = LabelEncoder()
df['pickup_datetime'] = enc.fit_transform(df['pickup_datetime'])
df['key'] = enc.fit_transform(df['key'])

df.drop('key',inplace = True , axis =1)

##Box plot viz for all numerical columns
for i in df.columns.to_list():
  sns.boxplot(df[i])
  plt.show()

sns.pairplot(df)

for i in df.columns.to_list():
  Q1 = df[i].quantile(0.25)
  Q3 = df[i].quantile(0.75)
  IQR = Q3 - Q1

  # identify outliers
  threshold = 1.5
  outliers = df[(df[i] < Q1 - threshold * IQR) | (df[i] > Q3 + threshold * IQR)]
  outliers[i].index
  df_out[i] = df.drop(outliers[i].index)
df_out

sns.heatmap(df.corr(),annot=True)

for i in df_out.columns.to_list():
  sns.boxplot(df_out[i])
  plt.show()

y = df['fare_amount']
x = df.drop('fare_amount',axis = 1)

X_train,X_test,y_train,y_test = train_test_split(x,y,train_size = 0.8)

##scaling

scale = StandardScaler()
x_train_scale = scale.fit_transform(X_train)
x_test_scale = scale.fit_transform(X_test)

model = LinearRegression()
a= model.fit(x_train_scale,y_train)

y_pred = a.predict(x_test_scale)
print(mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))